# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  yarn_config_cache: '$CI_PROJECT_DIR/.yarn'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: one-key-to-rule-them-all
  paths:
    - .yarn
    - cache/Cypress

test:
  image: cypress/base:10
  stage: test
  script:
    # - npm ci
    - yarn install --frozen-lockfile # the same to npm ci
    # print CI environment variables for reference
    - $(yarn bin)/print-env CI
    # make sure Cypress can run
    - yarn run cy:verify
    # start the server in the background
    - yarn run start & npx wait-on http://localhost:8081
    - yarn run cy:run
