image: cypress/base:12

stages:
  - test
  - test2


variables:
  yarn_config_cache: '$CI_PROJECT_DIR/cache/yarn'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_JOB_NAME}
  paths:
    - cache/yarn
    - cache/Cypress
    - node_modules

test:
  stage: test
  script:
    - yarn config set cache-folder ${yarn_config_cache}
    - yarn install --frozen-lockfile # the same to npm ci
    # print CI environment variables for reference
    - $(yarn bin)/print-env CI
    # make sure Cypress can run
    - yarn run cy:verify
    # start the server in the background
    - yarn run start &
    - yarn run cy:run

test2:
  stage: test2
  cache: {}
  script:
    - echo test2
