# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  yarn_config_cache: '$CI_PROJECT_DIR/.cache/yarn/v6'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: one-key-to-rule-them-all
  paths:
    - .cache/yarn/v6
    - cache/Cypress
    - node_modules

test:
  image: cypress/base:12
  stage: test
  script:
    - echo yarn_config_cache
    - yarn cache dir
    # - npm ci
    - yarn install --frozen-lockfile # the same to npm ci
    # print CI environment variables for reference
    - $(yarn bin)/print-env CI
    # make sure Cypress can run
    - yarn run cy:verify
    # start the server in the background
    - yarn run start &
    - yarn run cy:run
